server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/productService?createDatabaseIfNotExist=true
        username: root
        password: Ajin2000@
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:            
            ddl-auto: update   
    application:
        name: product-service
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"     
  endpoint:
    health:
      show-details: always       